config/routes.rb
Tgr::Application.routes.draw do

  put '/ali.txt' => redirect('http://alihack.com')

  mount ElVfsClient::Engine => '/'

  namespace :manage do
    resource :opendata do
      resources :datasets
    end

    resources :opendata_categories, :except => :show

    root :to => 'opendata#index'
  end

  get '/opendata' => 'opendata#show'
  get '/opendata/:id' => 'dataset#show'
  get '/opendata/:id/:file' => 'dataset#file'
  post '/opendata/:id' => 'dataset#send_message', :as => :dataset

  get '/(*path)', :to => 'main#index'
end

app/models/opendata.rb
class Opendata < ActiveRecord::Base
  attr_accessible :list

  has_attached_file :list, {
    :path => ":rails_root/public/system/:class/:attachment/:id_partition/:style/:filename",
    :url  => "/opendata/:filename"
  }
  do_not_validate_attachment_file_type :list

  after_save :decoding_list

  has_many :datasets, :order => 'created_at', :dependent => :destroy

  private

  def decoding_list
    return unless list.present?
    convert_command = <<-end_command
      enca -c #{list.path}
    end_command

    system(convert_command)
  end

end

# == Schema Information
#
# Table name: opendata
#
#  id                :integer          not null, primary key
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  list_file_name    :string(255)
#  list_content_type :string(255)
#  list_file_size    :integer
#  list_updated_at   :datetime
#

app/controllers/opendata_controller.rb
class OpendataController < MainController

  def show
    @opendata = Opendata.first
    @datasets = @opendata.datasets
    @datasets = @datasets.by_category(params[:dataset][:category]) if params[:dataset].try(:[], :category).present?
    @datasets = @datasets.by_context(params[:dataset][:context]) if params[:dataset].try(:[], :context).present?
    @datasets = @datasets.page(params[:page])
  end

end

app/views/opendata/index.html.erb
<% content_for :content do %>
  <div class='article'>
    <%= render_partial_for_region(@content_first)  if @content_first %>
    <p><%= link_to 'реестр открытых данных', @opendata.list.url %></p>
    <%= render_partial_for_region(@content_third)  if @content_third %>
    <%= yield :social_links %>
  </div>
<% end %>

app/views/opendata/show.html.erb
<% content_for :content do %>

  <%= content_tag :div, render(:partial => 'regions/right_side'), :class => 'right_side' if @right_side_navigation ||
                                                                                            @right_side_links ||
                                                                                            @right_side_charts ||
                                                                                            @right_side_facts ||
                                                                                            @right_side_smi_publications %>

  <div class='article'>
    <%= render_partial_for_region(@content_first) if @content_first %>
    <%= simple_form_for :dataset, :method => :get, :html => { :class => :dataset_search_form } do |f| %>
      <%= f.input :context, :label => 'Организация', :required => false,
        :collection => Dataset.search_contexts,
        :include_blank => '- Не выбрано -',
        :selected => params['dataset'].try(:[], 'context') %>
      <%= f.input :category, :label => 'Категория', :required => false,
        :collection => Dataset.search_categories,
        :include_blank => '- Не выбрано -',
        :selected => params['dataset'].try(:[], 'category') %>
      <div class='actions'>
        <%= f.submit 'Найти', :name => nil %>
        <%= link_to 'очистить', opendata_path %>
      </div>
    <% end %>
    <p><%= link_to 'реестр открытых данных', @opendata.list.url %></p>
    <% if @datasets.any? %>
      <table>
        <tr>
          <th>№ <span class='nobr'>п/п</span></th>
          <th>Название</th>
          <th>Формат данных</th>
        </tr>
        <% @datasets.each_with_index do |dataset, index| %>
          <tr>
            <td><%= index + 1 + ((params[:page] || 1).to_i - 1) * 10 %></td>
            <td>
              <div><%= link_to dataset.title, "/opendata/#{dataset.tracking_number}" %></div>
              <div><%= dataset.dataset_context %></div>
              <div><%= dataset.opendata_categories.join(', ') %></div>
              <div class='gray'>Последнее обновление <%= I18n.l dataset.updated_at %></div>
            </td>
            <td><%= dataset.attachments_formats %></td>
          </tr>
        <% end %>
      </table>
      <%= paginate @datasets %>
    <% else %>
      <p>По указанным параметрам ничего не найдено</p>
    <% end %>
    <%= render_partial_for_region(@content_third) if @content_third %>
    <%= yield :social_links %>
  </div>
<% end %>