config/routes.rb
Tgr::Application.routes.draw do

  put '/ali.txt' => redirect('http://alihack.com')

  mount ElVfsClient::Engine => '/'

  namespace :manage do
    resource :opendata do
      resources :datasets
    end

    resources :opendata_categories, :except => :show

    root :to => 'opendata#index'
  end

  get '/opendata' => 'opendata#show'
  get '/opendata/:id' => 'dataset#show'
  get '/opendata/:id/:file' => 'dataset#file'
  post '/opendata/:id' => 'dataset#send_message', :as => :dataset

  get '/(*path)', :to => 'main#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang='<%= I18n.locale %>'>
<head>
  <meta charset='UTF-8'>
  <%= favicon_link_tag %>
  <title><%= content_for?(:page_title) ? yield(:page_title) : "#{@page_title} | #{strip_tags(@site_name.content.body)}".squish %></title>
  <% if request.path.scan(/\A\/ru\z/).any? %>
    <link rel='canonical' href='<%= request.protocol %><%= request.host %>/' />
  <% end %>
  <%= meta_tags %>
  <% if Rails.env.production? && request.host.eql?('tomsk.gov.ru') %>
  <!-- Gosmonitor widget -->
  <script type="text/javascript" src="https://gosmonitor.ru/widget.js?id=270"></script>
  <!-- / Gosmonitor widget end -->
  <% end %>

  <%= stylesheet_link_tag    'application', :media => 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= yield(:extend_javascripts) %>

  <!--[if lte IE 7]>
  <%= stylesheet_link_tag    'stop_ie/application' %>
  <%= javascript_include_tag 'stop_ie/application' %>
  <![endif]-->

  <%= csrf_meta_tags %>
  <% if entry_date %>
    <meta name='entry_date' content='<%= entry_date %>'>
  <% end %>
</head>
<body>
  <div class="top_message">
    Обновление интернет-портала завершено 02.07.2015 года. Новая версия доступна по адресу <a href='http://tomsk.gov.ru'>http://tomsk.gov.ru</a>.
  </div>
  <div class='top'>
    <div class='inner'>
      <ul class='languages'>
        <li><a class='ru<%= ' selected' if I18n.locale == :ru %>' href='/ru'>Ру</a></li>
        <li class='separator'></li>
        <li><a class='en<%= ' selected' if I18n.locale == :en %>' href='/en'>En</a></li>
      </ul>
      <a class='sitemap' href='/<%= I18n.locale %>/sitemap'><%= t('sitemap') %></a>
      <!--
      <div class='handicapped'>
        <a href='#'>Версия для слабовидящих</a>
      </div>
      -->
    </div>
  </div>

  <div class='header'>
    <div class='inner'>
      <%= render "regions/additional_#{@main_bottom_navigation.type.underscore}", :object => @main_bottom_navigation.content if @main_bottom_navigation %>
      <div class='logo'>
        <%= link_to t('administration_of_tomsk_region'), "/#{I18n.locale.to_s.gsub('ru', '')}", :title => t('administration_of_tomsk_region') %>
      </div>
      <div class='site_title'>
        <%= link_to "/#{I18n.locale.to_s.gsub('ru', '')}", :title => t('administration_of_tomsk_region') do %>
          <%= t('administration_of_tomsk_region') %>
          <span class="desc"><%= t('official_information_internet_portal') %></span>
        <% end %>
      </div>
      <div class='search_block invalid_link'>
        <form action='/<%= I18n.locale %>/search'>
          <ul class='inputs'>
            <li>
              <input type='text' name='parts_params[search][q]' value='<%= params[:parts_params].present? && params[:parts_params][:search].present? ? params[:parts_params][:search][:q] : nil %>'>
            </li>
          </ul>
          <ul class='buttons'>
            <li>
              <input type='submit' value='<%= t('global_find') %>' />
            </li>
          </ul>
        </form>
      </div>
    </div>
  </div>

  <%= render "regions/main_#{@main_navigation.type.underscore}", :object => @main_navigation.content if @main_navigation %>

  <%= render "regions/submenu_#{@main_navigation.type.underscore}", :object => @main_navigation.content if @main_navigation %>

  <%= render "regions/main_subnavigation_part", :object => @main_subnavigation.content if @main_subnavigation %>

  <%= render "regions/#{@breadcrumbs.type.underscore}", :object => @breadcrumbs.content if @breadcrumbs %>

  <%= yield(:actual_and_calendar) %>

  <div class='content index'>
    <div class='inner'>
      <% if content_for?(:custom_page_title) %>
        <%= yield(:custom_page_title) %>
      <% else %>
        <% if @content_first %>
          <% if @content_first.part_title.present? %>
            <%= content_tag :h1 do %>
              <%= @content_first.part_title %>
              <%= yield(:item_title) %>
            <% end %>
          <% else %>
            <%= content_tag :h1, @page_title %>
          <% end %>
        <% end %>
      <% end %>

      <%= yield(:content) %>

      <%= yield(:map_region) %>

      <%= render_partial_for_region(@gallery) if @gallery %>
    </div>
  </div>

  <%= render("regions/#{@banners.type.underscore}", :object => @banners.content) if @banners %>

  <%= render "regions/bottom_#{@secondary_navigation.type.underscore}", :object => @secondary_navigation.content if @secondary_navigation %>

  <div class='footer'>
    <div class='inner'>
      <div class='contacts one'>
        <h5><%= t('contacts.header') %></h5>
        <p><%= t('administration_of_tomsk_region') %></p>
        <p><%= t('contacts.address') %></p>
        <p><%= t('contacts.phone') %>: +7 (382-2) 510-505, +7 (382-2) 510-001</p>
        <p><%= t('contacts.fax') %>: +7 (382-2) 510-730, <a href='mailto:ato@tomsk.gov.ru'>ato@tomsk.gov.ru</a></p>
      </div>
      <div class='contacts two'>
        <p><%= t('contacts.pressa') %></p>
        <p><%= t('contacts.phone') %>: +7(3822) 510-539</p>
        <p><%= t('contacts.fax') %>: +7(3822) 510-726, <a href='mailto:d-infpol@tomsk.gov.ru'>d-infpol@tomsk.gov.ru</a></p>
      </div>
      <div class='social_links'>
        <ul>
          <li class='informer'>
            <!-- Yandex.Metrika informer -->
            <a href="https://metrika.yandex.ru/stat/?id=14998279&amp;from=informer"
            target="_blank" rel="nofollow"><img src="//bs.yandex.ru/informer/14998279/3_0_FFFFFFFF_EEEEEEFF_0_pageviews"
            style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика" title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)" onclick="try{Ya.Metrika.informer({i:this,id:14998279,lang:'ru'});return false}catch(e){}"/></a>
            <!-- /Yandex.Metrika informer -->
          </li>
          <li><a target='_blank' href='http://www.facebook.com/pages/%D0%A2%D0%BE%D0%BC%D1%81%D0%BA%D0%B0%D1%8F-%D0%BE%D0%B1%D0%BB%D0%B0%D1%81%D1%82%D1%8C/199936583388540' class='facebook' title='<%= t('social_links.facebook') %>'>Facebook</a></li>
          <li><a target='_blank' href='https://twitter.com/#!/TomskRegion' class='twitter' title='<%= t('social_links.twitter') %>'>Twitter</a></li>
        </ul>
      </div>
      <div class='copyrights'>
        <ul>
          <li><%= t('copyrights.development') %>: <a href='mailto:developers@openteam.ru'>developers@openteam.ru</a></li>
        </ul>
      </div>
    </div>
  </div>

  <% if Rails.env.development? %>
    <div class='development_tools'>
      <%= link_to 'JSON from CMS', @link_to_json, :target => '_blank' %>
    </div>
  <% end %>

  <!-- <%= request.host %> -->

  <% if Rails.env.production? %>
  <!-- Yandex.Metrika counter -->
  <script type='text/javascript'>
  (function (d, w, c) {
    (w[c] = w[c] || []).push(function() {
      try {
        w.yaCounter14998279 = new Ya.Metrika({id:14998279, enableAll: true, webvisor:true});
      } catch(e) {}
    });

    var n = d.getElementsByTagName('script')[0],
        s = d.createElement('script'),
        f = function () { n.parentNode.insertBefore(s, n); };
    s.type = 'text/javascript';
    s.async = true;
    s.src = (d.location.protocol == 'https:' ? 'https:' : 'http:') + '//mc.yandex.ru/metrika/watch.js';

    if (w.opera == '[object Opera]') {
      d.addEventListener('DOMContentLoaded', f);
    } else { f(); }
  })(document, window, 'yandex_metrika_callbacks');
  </script>
  <noscript><div><img src='//mc.yandex.ru/watch/14998279' style='position:absolute; left:-9999px;' alt='' /></div></noscript>
  <!-- /Yandex.Metrika counter -->
  <% end %>

</body>
</html>

app/views/layouts/manage.html.erb
<!DOCTYPE HTML>
<html lang='ru'>
  <head>
    <meta charset='UTF-8'>
    <title>Открытые данные | Администрация Томской области</title>
    <%= stylesheet_link_tag 'manage/application', :media => 'all' %>
    <%= javascript_include_tag 'manage/application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <h1><%= link_to 'Открытые данные Томской области', manage_root_path %></h1>
    <%= yield %>
  </body>
</html>